#
# Copyright (c) 2020      Cisco Systems, Inc.  All rights reserved
# Copyright (c) 2025      UT-Battelle, LLC.    All rights reserved
#
#
# $COPYRIGHT$
#

noinst_PROGRAMS = test_add_del_err_codes \
                  test_add_del_err_codes_pthreads \
                  test_add_err_codes_usempi \
                  test_add_del_err_codes_usempi \
                  test_add_del_err_codes_usempif08

test_add_del_err_codes_SOURCES = \
        test_add_del_err_codes.c

test_add_del_err_codes_pthreads_SOURCES = \
        test_add_del_err_codes_pthreads.c

test_add_err_codes_usempi_SOURCES = \
        test_add_err_codes_usempi.f90

test_add_del_err_codes_usempi_SOURCES = \
        test_add_del_err_codes_usempi.f90

test_add_del_err_codes_usempif08_SOURCES = \
        test_add_del_err_codes_usempif08.f90


